[package]
name = "cypher-compsci"
version = "0.1.0"
authors = ["NyleCohen <nylecohen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bacon-cipher = "0.2.0"